# Generated by Django 2.1 on 2018-10-28 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trabajos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trabajo',
            old_name='author',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='trabajo',
            old_name='document',
            new_name='documento',
        ),
        migrations.RenameField(
            model_name='trabajo',
            old_name='name',
            new_name='titulo',
        ),
    ]
