# Generated by Django 2.1 on 2018-10-29 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajos', '0002_auto_20181028_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajo',
            name='categoria',
            field=models.CharField(choices=[('CC', 'Ciencias Computacionales'), ('CT', 'Ciencias de la Tierra'), ('CN', 'Ciencias Naturales'), ('CS', 'Ciencias Sociales'), ('CM', 'Ciencias Medicas')], default='CC', max_length=2),
        ),
    ]
